project:
  type: website
  output-dir: docs

format:
  html:
    theme:
        - quarto
        - custom.scss
    include-in-header:
      text: |
        <script type="text/javascript" src="javascript/eqn_annotation.js"></script>